---
- hosts: all
  become: yes
  become_method: sudo

  tasks:

    - name: install the latest version of vim
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - python
        - screen
        - tmux

