---
- hosts: all

  tasks:
  - name: Lookup JAVA_HOME
    set_fact:
      java_home: "{{ lookup('env', 'JAVA_HOME') }}"

  - name: Ensure JAVA_HOME is set
    assert:
      that: java_home is defined

  - name: Ensure hostname is set
    assert:
      that: hostname is defined

  - name: Set default port if not set
    set_fact:
      port: 443
    when: port is undefined

  - debug:
      msg: "{{ hostname }}:{{ port }}"

# - name: Download cert from host
#   command: openssl s_client -showcerts -connect $1:$2 </dev/null 2>/dev/null|openssl x509 -outform PEM > $1.pem
