---
- hosts: all

  tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson
    - name: install the latest version of vim
      package:
        name: vim
        state: latest

