---
- hosts: all

  tasks:

    - name: Disable ChallengeResponseAuthentication in sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        backup: yes
        owner: root
        group: root
        mode: 644
        line: 'ChallengeResponseAuthentication no'
        state: present

    - name: Disable PasswordAuthentication in sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        backup: yes
        owner: root
        group: root
        mode: 644
        line: 'PasswordAuthentication no'
        state: present

    - name: Disable UsePAM in sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        backup: yes
        owner: root
        group: root
        mode: 644
        line: 'UsePAM no'
        state: present

    - name: Restart sshd
      service:
        name: 'ssh'
        state: 'restarted'

