---
# This playbook deploys all osx tasks
- hosts: localhost
  remote_user: root

  vars:
    # Ensure all homebrew packages are installed
    homebrew_installed_packages:
      - pv
      - docker
      - docker-compose
      - docker-machine
      - hub
      - gradle
      - groovy
      - jenv
      - watch
      - tree
      - python
      - python3

  roles:
    - { role: geerlingguy.homebrew }
